/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.1 		*/
/*  Created On : 02-May-2020 11:38:55 AM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
;
/* Drop Tables */


DROP TABLE IF EXISTS `Lectures`
;
DROP TABLE IF EXISTS `Courses`
;
DROP TABLE IF EXISTS `Users`

/* Create Tables */

CREATE TABLE `Courses`
(
	`idCourse` INT NOT NULL AUTO_INCREMENT,
	`courseSubtitle` VARCHAR(50) NULL,
	`courseTitle` VARCHAR(50) NULL,
	`courseDescription` VARCHAR(50) NULL,
	`languaje` VARCHAR(50) NULL,
	`level` VARCHAR(50) NULL,
	`topic` VARCHAR(50) NULL,
	`module` VARCHAR(50) NULL,
	`primarylyTaught` VARCHAR(50) NULL,
	`imageCourse` VARCHAR(50) NULL,
	`videoPromotional` VARCHAR(50) NULL,
	`price` VARCHAR(50) NULL,
	`welcomeMessage` VARCHAR(50) NULL,
	`congratulationsMessage` VARCHAR(50) NULL,
	`idUsers` INT NULL,
	CONSTRAINT `PK_Courses` PRIMARY KEY (`idCourse` ASC)
)
;

CREATE TABLE `Lectures`
(
	`idLecture` INT NOT NULL ,
	`nameLecture` VARCHAR(50) NULL,
	`section` VARCHAR(50) NULL,
	`description` VARCHAR(50) NULL,
	`typeFile` VARCHAR(50) NULL,
	`file` VARCHAR(50) NULL,
	`video` VARCHAR(500) NULL,
	`idCourse` INT NULL,
	CONSTRAINT `PK_Lectures` PRIMARY KEY (`idLecture` ASC)
)

;

CREATE TABLE `Users`
(
	`idUsers` INT NOT NULL AUTO_INCREMENT,
	`firstName` VARCHAR(20) NOT NULL,
	`lastName` VARCHAR(20) NULL,
	`email` TEXT NOT NULL,
	`phoneNumber` VARCHAR(20) NULL,
	`education` VARCHAR(50) NULL,
	`userType` VARCHAR(50) NOT NULL,
	`password` TEXT NOT NULL,
	`question1` VARCHAR(100) NULL,
	`question2` VARCHAR(100) NULL,
	`question3` VARCHAR(100) NULL,
	CONSTRAINT `PK_User` PRIMARY KEY (`idUsers` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `Courses`
 ADD INDEX `IXFK_Courses_Users` (`idUsers` ASC)
;

ALTER TABLE `Lectures`
 ADD INDEX `IXFK_Lectures_Courses` (`idCourse` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `Courses`
 ADD CONSTRAINT `FK_Courses_Users`
	FOREIGN KEY (`idUsers`) REFERENCES `Users` (`idUsers`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Lectures`
 ADD CONSTRAINT `FK_Lectures_Courses`
	FOREIGN KEY (`idCourse`) REFERENCES `Courses` (`idCourse`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
;
